const STORAGE_KEYS = {
  customResources: "fieldOps.customResources",
  customSites: "fieldOps.customSites",
  manualTasks: "fieldOps.manualTasks",
  customRegions: "fieldOps.customRegions",
  customSkills: "fieldOps.customSkills",
  activeView: "fieldOps.activeView",
  atlasTab: "fieldOps.atlasTab",
  manualOverrides: "fieldOps.manualOverrides",
  settings: "fieldOps.settings",
  siteDocuments: "fieldOps.siteDocuments",
  notificationFilter: "fieldOps.notificationFilter",
  customTasks: "fieldOps.customTasks",
  taskOverrides: "fieldOps.taskOverrides",
  suppressedTasks: "fieldOps.suppressedTasks",
  resourceOverrides: "fieldOps.resourceOverrides",
  siteOverrides: "fieldOps.siteOverrides",
  suppressedResources: "fieldOps.suppressedResources",
  regionRenames: "fieldOps.regionRenames",
  completions: "fieldOps.completions",
  planHistory: "fieldOps.planHistory"
};

const defaultTechnicians = [
  {
    id: "tech-lead-alpha",
    name: "Tech Lead - Alpha",
    base: "Michigan",
    region: "Midwest",
    classification: "Technical Leader",
    coverage: "Installation visit, email support, L3 guidance",
    lat: 42.3314,
    lng: -83.0458,
    skills: ["TECH_LEAD", "INSTALLATION_SUPPORT", "EMAIL_SUPPORT", "L3_SUPPORT", "PARTNER_ESCALATION"],
    start: "08:30",
    end: "17:30",
    maxHours: 8,
    maxTravel: 120,
    dispatchable: false,
    color: "#176b5b"
  },
  {
    id: "senior-fse-alpha",
    name: "Senior FSE - Alpha",
    base: "Kansas City, MO",
    region: "Midwest",
    classification: "Senior FSE",
    coverage: "L2/L3 support, partner escalation, urgent onsite",
    lat: 39.0997,
    lng: -94.5786,
    skills: ["SENIOR_FSE", "L2_SUPPORT", "L3_SUPPORT", "PARTNER_ESCALATION", "URGENT_ONSITE", "INSTALLATION_SUPPORT"],
    start: "08:30",
    end: "17:30",
    maxHours: 8,
    maxTravel: 420,
    color: "#246a92"
  },
  {
    id: "senior-fse-beta",
    name: "Senior FSE - Beta",
    base: "Charlotte, NC",
    region: "Southeast",
    classification: "Senior FSE",
    coverage: "L2/L3 support, partner escalation, urgent onsite",
    lat: 35.2271,
    lng: -80.8431,
    skills: ["SENIOR_FSE", "L2_SUPPORT", "L3_SUPPORT", "PARTNER_ESCALATION", "URGENT_ONSITE", "INSTALLATION_SUPPORT"],
    start: "08:30",
    end: "17:30",
    maxHours: 8,
    maxTravel: 420,
    color: "#9b6a15"
  },
  {
    id: "dedicated-ose-alpha",
    name: "Dedicated OSE - Alpha",
    base: "Marlborough, MA",
    region: "Northeast",
    classification: "Dedicated OSE",
    assignedSiteId: "site-healthcare-ne",
    coverage: "Healthcare Client NE onsite ownership",
    lat: 42.3501,
    lng: -71.5523,
    skills: ["DIRECT_SITE_COVERAGE", "HOTLINE_24_7", "L1_SUPPORT", "L2_SUPPORT", "L3_SUPPORT", "ONSITE_PRESENCE", "INSTALLATION_SUPPORT"],
    start: "08:00",
    end: "17:00",
    maxHours: 9,
    maxTravel: 90,
    color: "#a33a32"
  },
  {
    id: "ose-tech-a",
    name: "OSE Technician A",
    base: "New Jersey",
    region: "Northeast",
    classification: "OSE",
    assignedSiteId: "site-cancer-center-ny",
    coverage: "Cancer Center NY and Imaging Client LI day coverage",
    lat: 40.7357,
    lng: -74.1724,
    skills: ["DIRECT_SITE_COVERAGE", "HOTLINE_24_7", "L1_SUPPORT", "L2_SUPPORT", "L3_SUPPORT", "ONSITE_PRESENCE", "INSTALLATION_SUPPORT"],
    start: "08:00",
    end: "17:00",
    maxHours: 9,
    maxTravel: 150,
    color: "#5f7f3d"
  },
  {
    id: "ose-tech-b",
    name: "OSE Technician B",
    base: "New Jersey",
    region: "Northeast",
    classification: "OSE",
    assignedSiteId: "site-imaging-li",
    coverage: "Cancer Center NY and Imaging Client LI day coverage",
    lat: 40.7357,
    lng: -74.1724,
    skills: ["DIRECT_SITE_COVERAGE", "HOTLINE_24_7", "L1_SUPPORT", "L2_SUPPORT", "L3_SUPPORT", "ONSITE_PRESENCE", "INSTALLATION_SUPPORT"],
    start: "08:00",
    end: "17:00",
    maxHours: 9,
    maxTravel: 150,
    color: "#6b5aa6"
  },
  {
    id: "dedicated-ose-beta",
    name: "Dedicated OSE - Beta",
    base: "Holyoke, MA",
    region: "Northeast",
    classification: "Dedicated OSE",
    assignedSiteId: "site-lab-ma",
    coverage: "Laboratory Client MA onsite ownership",
    lat: 42.2043,
    lng: -72.6162,
    skills: ["DIRECT_SITE_COVERAGE", "HOTLINE_24_7", "L1_SUPPORT", "L2_SUPPORT", "L3_SUPPORT", "ONSITE_PRESENCE", "INSTALLATION_SUPPORT"],
    start: "08:00",
    end: "17:00",
    maxHours: 9,
    maxTravel: 90,
    color: "#b05c2c"
  },
  {
    id: "dedicated-ose-gamma",
    name: "Dedicated OSE - Gamma",
    base: "Indianapolis, IN",
    region: "Midwest",
    classification: "Dedicated OSE",
    assignedSiteId: "site-lab-in",
    coverage: "Laboratory Client IN onsite ownership",
    lat: 39.7684,
    lng: -86.1581,
    skills: ["DIRECT_SITE_COVERAGE", "HOTLINE_24_7", "L1_SUPPORT", "L2_SUPPORT", "L3_SUPPORT", "ONSITE_PRESENCE", "INSTALLATION_SUPPORT"],
    start: "08:00",
    end: "17:00",
    maxHours: 9,
    maxTravel: 90,
    color: "#167a88"
  },
  {
    id: "night-ose-alpha",
    name: "Night OSE - Alpha",
    base: "Long Island, NY",
    region: "Northeast",
    classification: "Night OSE",
    assignedSiteId: "site-imaging-li",
    coverage: "Imaging Client LI night shift ownership",
    lat: 40.7891,
    lng: -73.135,
    skills: ["NIGHT_SITE_COVERAGE", "HOTLINE_24_7", "L1_SUPPORT", "L2_SUPPORT", "ONSITE_PRESENCE"],
    start: "20:00",
    end: "06:00",
    maxHours: 10,
    maxTravel: 90,
    color: "#375a7f"
  },
  {
    id: "senior-mw-sw-alpha",
    name: "Senior Middleware SW - Alpha",
    base: "Philadelphia, PA",
    region: "Northeast",
    classification: "Senior Middleware SW",
    coverage: "Middleware L2/L3 remote support",
    lat: 39.9526,
    lng: -75.1652,
    skills: ["MIDDLEWARE", "L2_SUPPORT", "L3_SUPPORT", "EMAIL_SUPPORT", "PARTNER_ESCALATION"],
    start: "08:30",
    end: "17:30",
    maxHours: 8,
    maxTravel: 60,
    color: "#4c6b55"
  },
  {
    id: "mw-sw-alpha",
    name: "Middleware SW - Alpha",
    base: "Pennsylvania",
    region: "Northeast",
    classification: "Middleware SW",
    coverage: "Middleware remote support",
    lat: 40.2732,
    lng: -76.8867,
    skills: ["MIDDLEWARE", "L2_SUPPORT", "EMAIL_SUPPORT", "PARTNER_ESCALATION"],
    start: "08:30",
    end: "17:30",
    maxHours: 8,
    maxTravel: 60,
    color: "#8a6f36"
  },
  {
    id: "mw-sw-beta",
    name: "Middleware SW - Beta",
    base: "New York, NY",
    region: "Northeast",
    classification: "Middleware SW",
    coverage: "Middleware remote support",
    lat: 40.7128,
    lng: -74.006,
    skills: ["MIDDLEWARE", "L2_SUPPORT", "EMAIL_SUPPORT", "PARTNER_ESCALATION"],
    start: "08:30",
    end: "17:30",
    maxHours: 8,
    maxTravel: 60,
    color: "#7b5768"
  }
];

const defaultSites = [
  {
    id: "site-cancer-center-ny",
    customer: "Cancer Center NY",
    site: "Cancer Center NY",
    label: "Cancer Center NY - Manhattan, NY",
    city: "Manhattan, NY",
    region: "Northeast",
    lat: 40.7644,
    lng: -73.9566,
    contract: "direct",
    preferredTechIds: ["ose-tech-b", "ose-tech-a", "senior-fse-alpha", "senior-fse-beta"]
  },
  {
    id: "site-imaging-li",
    customer: "Imaging Client LI",
    site: "Imaging Client LI",
    label: "Imaging Client LI - Long Island, NY",
    city: "Long Island, NY",
    region: "Northeast",
    lat: 40.7891,
    lng: -73.135,
    contract: "direct",
    preferredTechIds: ["night-ose-alpha", "ose-tech-b", "ose-tech-a", "senior-fse-alpha", "senior-fse-beta"]
  },
  {
    id: "site-lab-in",
    customer: "Laboratory Client IN",
    site: "Laboratory Client IN",
    label: "Laboratory Client IN - Indianapolis, IN",
    city: "Indianapolis, IN",
    region: "Midwest",
    lat: 39.7684,
    lng: -86.1581,
    contract: "direct",
    preferredTechIds: ["dedicated-ose-gamma", "senior-fse-alpha", "senior-fse-beta"]
  },
  {
    id: "site-lab-ma",
    customer: "Laboratory Client MA",
    site: "Laboratory Client MA",
    label: "Laboratory Client MA - Holyoke, MA",
    city: "Holyoke, MA",
    region: "Northeast",
    lat: 42.2043,
    lng: -72.6162,
    contract: "direct",
    preferredTechIds: ["dedicated-ose-beta", "senior-fse-alpha", "senior-fse-beta"]
  },
  {
    id: "site-healthcare-ne",
    customer: "Healthcare Client NE",
    site: "Healthcare Client NE",
    label: "Healthcare Client NE - Boston, MA",
    city: "Boston, MA",
    region: "Northeast",
    lat: 42.337,
    lng: -71.1056,
    contract: "direct",
    preferredTechIds: ["dedicated-ose-alpha", "senior-fse-alpha", "senior-fse-beta"]
  },
  {
    id: "site-diagnostics-sd",
    customer: "Diagnostics Partner SD",
    site: "Diagnostics Partner SD",
    label: "Diagnostics Partner SD - San Diego, CA",
    city: "San Diego, CA",
    region: "Remote",
    lat: 32.7157,
    lng: -117.1611,
    contract: "partner",
    preferredTechIds: ["tech-lead-alpha", "senior-fse-alpha", "senior-fse-beta", "senior-mw-sw-alpha", "mw-sw-alpha", "mw-sw-beta"]
  },
  {
    id: "site-medical-tn",
    customer: "Medical Partner TN",
    site: "Medical Partner TN",
    label: "Medical Partner TN - Nashville, TN",
    city: "Nashville, TN",
    region: "Southeast",
    lat: 36.1627,
    lng: -86.7816,
    contract: "partner",
    preferredTechIds: ["senior-fse-beta", "senior-fse-alpha", "tech-lead-alpha"]
  },
  {
    id: "site-medical-ca",
    customer: "Medical Partner CA",
    site: "Medical Partner CA",
    label: "Medical Partner CA - Irvine, CA",
    city: "Irvine, CA",
    region: "West",
    lat: 33.6846,
    lng: -117.8265,
    contract: "partner",
    preferredTechIds: ["senior-fse-alpha", "senior-fse-beta", "tech-lead-alpha"]
  },
  {
    id: "remote-middleware",
    customer: "Internal",
    site: "Middleware support",
    label: "Middleware support - USA remote",
    city: "USA remote",
    region: "Remote",
    lat: 39.8283,
    lng: -98.5795,
    contract: "internal",
    preferredTechIds: ["senior-mw-sw-alpha", "mw-sw-alpha", "mw-sw-beta"]
  }
];

const defaultBaselineTasks = [
  {
    id: "DIR-001",
    title: "Cancer Center NY dedicated onsite coverage",
    siteId: "site-cancer-center-ny",
    priority: "critical",
    duration: 540,
    windowStart: "08:00",
    windowEnd: "17:00",
    skill: "DIRECT_SITE_COVERAGE",
    sla: "Direct client - H24 responsibility",
    type: "direct_site",
    contract: "direct",
    defaultOwnerId: "ose-tech-a",
    preferredTechIds: ["ose-tech-a", "ose-tech-b"],
    hardEligibleTechIds: ["ose-tech-a", "ose-tech-b"]
  },
  {
    id: "DIR-002",
    title: "Imaging Client LI night coverage",
    siteId: "site-imaging-li",
    priority: "critical",
    duration: 600,
    windowStart: "20:00",
    windowEnd: "06:00",
    skill: "NIGHT_SITE_COVERAGE",
    sla: "Direct client - night onsite",
    type: "direct_site",
    contract: "direct",
    defaultOwnerId: "night-ose-alpha",
    preferredTechIds: ["night-ose-alpha"],
    hardEligibleTechIds: ["night-ose-alpha"]
  },
  {
    id: "DIR-003",
    title: "Imaging Client LI day coverage",
    siteId: "site-imaging-li",
    priority: "critical",
    duration: 540,
    windowStart: "08:00",
    windowEnd: "17:00",
    skill: "DIRECT_SITE_COVERAGE",
    sla: "Direct client - day onsite",
    type: "direct_site",
    contract: "direct",
    defaultOwnerId: "ose-tech-b",
    preferredTechIds: ["ose-tech-b", "ose-tech-a"],
    hardEligibleTechIds: ["ose-tech-b", "ose-tech-a"]
  },
  {
    id: "DIR-004",
    title: "Laboratory Client IN dedicated site",
    siteId: "site-lab-in",
    priority: "critical",
    duration: 540,
    windowStart: "08:00",
    windowEnd: "17:00",
    skill: "DIRECT_SITE_COVERAGE",
    sla: "Direct client - onsite ownership",
    type: "direct_site",
    contract: "direct",
    defaultOwnerId: "dedicated-ose-gamma",
    preferredTechIds: ["dedicated-ose-gamma"],
    hardEligibleTechIds: ["dedicated-ose-gamma"]
  },
  {
    id: "DIR-005",
    title: "Laboratory Client MA dedicated site",
    siteId: "site-lab-ma",
    priority: "critical",
    duration: 540,
    windowStart: "08:00",
    windowEnd: "17:00",
    skill: "DIRECT_SITE_COVERAGE",
    sla: "Direct client - onsite ownership",
    type: "direct_site",
    contract: "direct",
    defaultOwnerId: "dedicated-ose-beta",
    preferredTechIds: ["dedicated-ose-beta"],
    hardEligibleTechIds: ["dedicated-ose-beta"]
  },
  {
    id: "DIR-006",
    title: "Healthcare Client NE dedicated site",
    siteId: "site-healthcare-ne",
    priority: "critical",
    duration: 540,
    windowStart: "08:00",
    windowEnd: "17:00",
    skill: "DIRECT_SITE_COVERAGE",
    sla: "Direct client - onsite ownership",
    type: "direct_site",
    contract: "direct",
    defaultOwnerId: "dedicated-ose-alpha",
    preferredTechIds: ["dedicated-ose-alpha"],
    hardEligibleTechIds: ["dedicated-ose-alpha"]
  },
  {
    id: "PAR-001",
    title: "Customer HW remote support — weekly rotation",
    siteId: "remote-hotline",
    site: "USA Remote",
    customer: "All customers",
    region: "Remote",
    priority: "high",
    duration: 180,
    windowStart: "08:30",
    windowEnd: "17:30",
    skill: "PARTNER_ESCALATION",
    sla: "HW remote support Mon-Fri 08:30-17:30 — shared across all partners",
    type: "remote_support",
    contract: "direct",
    serviceMode: "remote",
    preferredTechIds: ["senior-fse-alpha", "senior-fse-beta", "tech-lead-alpha"]
  },
  {
    id: "SW-001",
    title: "Customer SW remote support — weekly rotation",
    siteId: "remote-middleware",
    priority: "medium",
    duration: 180,
    windowStart: "08:30",
    windowEnd: "17:30",
    skill: "MIDDLEWARE",
    sla: "Business hours remote support",
    type: "remote_support",
    contract: "internal",
    serviceMode: "remote",
    preferredTechIds: ["senior-mw-sw-alpha", "mw-sw-alpha", "mw-sw-beta"]
  }
];

const defaultScenarioTasks = [
  {
    id: "DEMO-001",
    title: "Cancer Center NY urgent L3 analyzer intervention",
    siteId: "site-cancer-center-ny",
    priority: "critical",
    duration: 180,
    windowStart: "10:00",
    windowEnd: "16:00",
    skill: "URGENT_ONSITE",
    sla: "Direct client urgent escalation",
    type: "field_escalation",
    contract: "direct",
    source: "scenario",
    intakeCategory: "Unexpected direct customer support",
    preferredTechIds: ["senior-fse-alpha", "senior-fse-beta"]
  },
  {
    id: "DEMO-003",
    title: "Partner ticket burst from Salesforce",
    siteId: "remote-hotline",
    site: "USA Remote",
    customer: "All customers",
    region: "Remote",
    priority: "high",
    duration: 180,
    windowStart: "08:30",
    windowEnd: "17:30",
    skill: "PARTNER_ESCALATION",
    sla: "Partner backlog support",
    type: "partner_escalation",
    contract: "direct",
    serviceMode: "remote",
    source: "scenario",
    intakeCategory: "Partner L2/L3 escalation",
    preferredTechIds: ["senior-fse-alpha", "senior-fse-beta", "tech-lead-alpha"]
  },
  {
    id: "DEMO-004",
    title: "Middleware interface validation request",
    siteId: "remote-middleware",
    priority: "medium",
    duration: 150,
    windowStart: "09:00",
    windowEnd: "15:00",
    skill: "MIDDLEWARE",
    sla: "Same week middleware follow-up",
    type: "remote_support",
    contract: "internal",
    serviceMode: "remote",
    source: "scenario",
    intakeCategory: "Middleware support",
    preferredTechIds: ["senior-mw-sw-alpha", "mw-sw-alpha", "mw-sw-beta"],
    hardEligibleTechIds: ["senior-mw-sw-alpha", "mw-sw-alpha", "mw-sw-beta"]
  }
];

const baseRegions = ["Northeast", "Midwest", "Southeast", "West", "Remote"];

const sitePmPlans = [
  {
    "siteId": "site-cancer-center-ny",
    "site": "Cancer Center NY",
    "city": "Manhattan, NY",
    "owner": "OSE Technician A",
    "contract": "Direct - H24, anomaly L1/L2/L3, onsite presence",
    "commissionedAt": "2025-12-10",
    "dueDate": "2026-07-15",
    "modules": [
      "Smart Bridge Module",
      "Sealer Module",
      "Input/Output Module X Open Access",
      "Storage and Retrieval Module",
      "Decapper Module",
      "Recapper module"
    ]
  },
  {
    "siteId": "site-imaging-li",
    "site": "Imaging Client LI",
    "city": "Long Island, NY",
    "owner": "Night OSE - Alpha night / OSE Technician B day",
    "contract": "Direct - H24, anomaly L1/L2/L3, onsite presence",
    "commissionedAt": "2024-10-05",
    "dueDate": "2026-05-05",
    "modules": [
      "Smart Bridge Module",
      "Aliquoter Module",
      "Sealer Module",
      "Decapper Module",
      "Recapper module"
    ]
  },
  {
    "siteId": "site-lab-in",
    "site": "Laboratory Client IN",
    "city": "Indianapolis, IN",
    "owner": "Dedicated OSE - Gamma",
    "contract": "Direct - dedicated onsite ownership",
    "commissionedAt": "2025-06-20",
    "dueDate": "2026-06-20",
    "modules": [
      "Input/Output Module X Open Access",
      "Storage and Retrieval Module",
      "Bulk Input Module",
      "Rack Input Module",
      "Track System"
    ]
  },
  {
    "siteId": "site-lab-ma",
    "site": "Laboratory Client MA",
    "city": "Holyoke, MA",
    "owner": "Dedicated OSE - Beta",
    "contract": "Direct - dedicated onsite ownership",
    "commissionedAt": "2024-11-12",
    "dueDate": "2026-05-12",
    "modules": [
      "Alinity ci-series IM",
      "Cobas 8000",
      "Smart Bridge Module",
      "Track System"
    ]
  },
  {
    "siteId": "site-healthcare-ne",
    "site": "Healthcare Client NE",
    "city": "Boston, MA",
    "owner": "Dedicated OSE - Alpha",
    "contract": "Direct - dedicated onsite ownership",
    "commissionedAt": "2026-03-18",
    "dueDate": "2026-09-18",
    "modules": [
      "Liquid Handling Robot for BloodBanks",
      "Aliquoter Module",
      "Sample Integrity Module (SIM)",
      "Smart Bridge Module"
    ]
  },
  {
    "siteId": "site-diagnostics-sd",
    "site": "Diagnostics Partner SD",
    "city": "San Diego, CA",
    "owner": "Senior FSE / Middleware queue",
    "contract": "Partner - remote hotline and L2/L3 escalation",
    "dueDate": "",
    "modules": []
  },
  {
    "siteId": "site-medical-tn",
    "site": "Medical Partner TN",
    "city": "Nashville, TN",
    "owner": "Partner L1 / internal L2-L3",
    "contract": "Partner - escalation via Salesforce",
    "dueDate": "",
    "modules": []
  },
  {
    "siteId": "site-medical-ca",
    "site": "Medical Partner CA",
    "city": "Irvine, CA",
    "owner": "Partner L1 / internal L2-L3",
    "contract": "Partner - escalation via Salesforce",
    "dueDate": "",
    "modules": []
  }
];
